# Generated by Django 4.2.1 on 2023-06-06 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_alter_film_release_date_alter_poster_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 18, 28, 1, 475893, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 18, 28, 1, 476883, tzinfo=datetime.timezone.utc)),
        ),
    ]
