# Generated by Django 4.2.1 on 2023-06-07 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_alter_film_release_date_alter_review_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(related_name='films', to='films.category'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 23, 13, 59, 427750, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 23, 13, 59, 428885, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='film',
            name='producers',
            field=models.ManyToManyField(to='films.producer'),
        ),
    ]
