# Generated by Django 4.2.2 on 2023-06-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_forecaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecaster',
            old_name='forecaster',
            new_name='user',
        ),
    ]
