# Generated by Django 4.2.1 on 2023-06-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_alter_rental_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='rent.customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='rent.vehicle'),
        ),
        migrations.AlterField(
            model_name='rentalrate',
            name='vehicle_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_size', to='rent.vehiclesize'),
        ),
        migrations.AlterField(
            model_name='rentalrate',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type', to='rent.vehicletype'),
        ),
    ]
