# Generated by Django 4.2.1 on 2023-06-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_date_completion_alter_todo_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='has_been_done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
