# Generated by Django 4.2.1 on 2023-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='thumbnail_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
