# Generated by Django 4.2.1 on 2023-06-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
